name: ReleasePackage

on:
  workflow_call:
    inputs:
      packageName:
        required: true
        type: string
      branchName:
        required: true
        type: string
      pullRequestId:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      packageName:
        type: choice
        description: Select the package
        options:
        - package3
        - package4
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}-release-package

jobs:
  # Run only if the latest commit is related to a release > release(package): new version X.XX.XX
  ReleasePackage:
    name: Release package
    runs-on: ubuntu-latest
    steps:

      - name: Checkout from specific branch
        if: inputs.branchName
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branchName }}

      - name: Checkout current branch
        if: ${{ !inputs.branchName }}
        uses: actions/checkout@v3

      - name: display package info
        run: |
          echo "Current Branch: ${{ github.ref_name }}"
          echo "Requested Branch: ${{ inputs.branchName }}"
          echo "Package name: ${{ inputs.packageName }}"
          echo "Pull request id: ${{ inputs.pullRequestId }}"
          # echo "Package version: ${{ steps.packageVersion.outputs.value }}"
          # echo "Package major version: ${{ steps.packageInfo.outputs.packageMajorVersion }}"

