name: TestPRWorkflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches:
      - "test-**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: |
            echo "GITHUB_REF: ${GITHUB_REF##*/}";
            echo "github.event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}";
            echo "github.event.workflow_run.head_ref: ${{ github.event.workflow_run.head_ref }}";
            echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}";
            echo "github.ref: ${{ github.ref }}";
            echo "github.ref_name: ${{ github.ref_name }}";
            echo "github.sha: ${{ github.sha }}";
            echo "github.head_ref: ${{ github.head_ref }}";
