name: TestWorkflow

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - chore-test-**

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Event type: ${{ github.event_name }}"
          echo "BranchName: ${{ github.ref_name }}"
      - name: get package info
        id: packageInfo
        run: |
          # use printf to handle correclty single quotes in commit message
          printf -v commitMessage "${{ github.event.head_commit.message }}"
          commitTitle=$(echo $commitMessage | head -n 1)
          echo "name=$(echo $commitTitle | sed -e 's/release(\([^()]*\)).*/\1/')" >> $GITHUB_OUTPUT
          echo "version=$(echo $commitTitle | sed -e 's/.* \([0-9]\+.[0-9]\+.[0-9]\+\).*/\1/')" >> $GITHUB_OUTPUT

      - name: show package info
        run: |
          echo "Package name: ${{ steps.packageInfo.outputs.name }}"
          echo "Package version: ${{ steps.packageInfo.outputs.version }}"

