name: TriggerCreatePreReleasePR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # branches:
    #   - 'changeset-release-*'

concurrency:
  group: ${{ github.run_id }}-${{ github.ref }}-trigger-create-prerelease-pr
  cancel-in-progress: true

jobs:
  prerequisites:
    name: Prerequisites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: get package name
        id: packageName
        run: |
          echo "name=$(echo '${{ github.event.pull_request.title }}' | head -n 1 | sed -e 's/release(\([^()]*\)).*/\1/')" >> $GITHUB_OUTPUT

      - name: Get CI info (affected packages and shouldRunVisualTesting)
        id: pr-info
        run: |
          echo "PR head: ${{ github.event.pull_request.head.sha }}"
          echo "PR ID: ${{ github.event.pull_request.number}}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR TITLE: ${{ github.event.pull_request.title }}"
          echo "PACKAGE NAME: ${{ steps.packageName.outputs.name }}"
